// Generated by https://quicktype.io

export interface PokemonResponse {
  count: number;
  next?: string;
  previous?: string;
  results: SmallPokemons[];
}

export interface SmallPokemons {
  name: string;
  url: string;
  id: number;
  img: string;
}
